name: tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 */3 * * *"


jobs:
  tests:
    name: ./test.sh
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - run: ./test.sh
