name: tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 */4 * * *"


jobs:
  tests:
    name: ./test.sh
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./test.sh
